# SupplyPrescript

# Sprint 5 - Feature Engineering

## Objective

Create new business features that improve the predictive power of the machine learning model.

In [1]:
import pandas as pd

pd.set_option("display.max_columns", None)

In [2]:
df = pd.read_csv("../data/processed/cleaned_logistics_dataset.csv")

df.head()

,Origin_Port,Destination_Port,Transport_Mode,Product_Category,Distance_km,Weight_MT,Fuel_Price_Index,Geopolitical_Risk_Score,Weather_Condition,Carrier_Reliability_Score,Lead_Time_Days,Disruption_Occurred,Year,Month,Day,DayOfWeek
0,7,4,1,4,5930.83,197.42,2.43,5.0,2,0.865,41.39,1,2025,10,16,4
1,7,7,1,0,14285.36,237.24,2.30,7.5,4,0.592,40.92,1,2024,4,24,6
2,5,4,1,2,11113.91,427.42,1.78,5.6,3,0.673,11.54,0,2024,1,26,0
3,1,3,1,1,9180.55,170.66,3.20,0.8,2,0.832,53.13,1,2024,10,8,5
4,1,8,0,2,2762.27,434.96,2.77,1.9,1,0.741,0.50,1,2024,9,7,2

In [3]:
df["Cost_Per_KM"] = df["Fuel_Price_Index"] / df["Distance_km"]

In [4]:
df["Risk_LeadTime"] = (
    df["Geopolitical_Risk_Score"] *
    df["Lead_Time_Days"]
)

In [5]:
df["Weight_Per_KM"] = (
    df["Weight_MT"] /
    df["Distance_km"]
)

In [6]:
df["Risk_Reliability"] = (
    df["Geopolitical_Risk_Score"] *
    (1 - df["Carrier_Reliability_Score"])
)

In [7]:
df["High_Risk"] = (
    df["Geopolitical_Risk_Score"] >= 7
).astype(int)

In [8]:
df.head()

,Origin_Port,Destination_Port,Transport_Mode,Product_Category,Distance_km,Weight_MT,Fuel_Price_Index,Geopolitical_Risk_Score,Weather_Condition,Carrier_Reliability_Score,Lead_Time_Days,Disruption_Occurred,Year,Month,Day,DayOfWeek,Cost_Per_KM,Risk_LeadTime,Weight_Per_KM,Risk_Reliability,High_Risk
0,7,4,1,4,5930.83,197.42,2.43,5.0,2,0.865,41.39,1,2025,10,16,4,0.000410,206.950,0.033287,0.6750,0
1,7,7,1,0,14285.36,237.24,2.30,7.5,4,0.592,40.92,1,2024,4,24,6,0.000161,306.900,0.016607,3.0600,1
2,5,4,1,2,11113.91,427.42,1.78,5.6,3,0.673,11.54,0,2024,1,26,0,0.000160,64.624,0.038458,1.8312,0
3,1,3,1,1,9180.55,170.66,3.20,0.8,2,0.832,53.13,1,2024,10,8,5,0.000349,42.504,0.018589,0.1344,0
4,1,8,0,2,2762.27,434.96,2.77,1.9,1,0.741,0.50,1,2024,9,7,2,0.001003,0.950,0.157465,0.4921,0

In [9]:
import os

os.makedirs("../data/features", exist_ok=True)

In [10]:
df.to_csv(
    "../data/features/feature_dataset.csv",
    index=False
)

In [11]:
import os

os.listdir("../data/features")

['feature_dataset.csv']

# Feature Engineering Summary

Created Features

- Cost_Per_KM
- Risk_LeadTime
- Weight_Per_KM
- Risk_Reliability
- High_Risk

These engineered features combine multiple business variables into more informative predictors that may improve model performance.