In [ ]:
import pandas as pd
from connection import conn

In [11]:
df=pd.read_sql("SELECT * FROM raw1", con=conn)
df.head()

C:\Users\thean\AppData\Local\Temp\ipykernel_17636\2796152824.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql("SELECT * FROM raw1", con=conn)

,Shipment_ID,Date,Origin_Port,Destination_Port,Transport_Mode,Product_Category,Distance_km,Weight_MT,Fuel_Price_Index,Geopolitical_Risk_Score,Weather_Condition,Carrier_Reliability_Score,Lead_Time_Days,Disruption_Occurred
0,SC-10000,2025-10-16,Singapore,Los Angeles,Rail,Textiles,5930.83,197.42,2.43,5.0,Hurricane,0.865,41.39,True
1,SC-10001,2024-04-24,Singapore,Shanghai,Rail,Automotive,14285.36,237.24,2.30,7.5,Storm,0.592,40.92,True
2,SC-10002,2024-01-26,Rotterdam,Los Angeles,Rail,Perishables,11113.91,427.42,1.78,5.6,Rain,0.673,11.54,False
3,SC-10003,2024-10-08,Busan,Hamburg,Rail,Electronics,9180.55,170.66,3.20,0.8,Hurricane,0.832,53.13,True
4,SC-10004,2024-09-07,Busan,Singapore,Air,Perishables,2762.27,434.96,2.77,1.9,Fog,0.741,0.50,True

In [12]:
df.shape

(5000, 14)

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Shipment_ID                5000 non-null   str
 1   Date                       5000 non-null   datetime64[s]
 2   Origin_Port                5000 non-null   str
 3   Destination_Port           5000 non-null   str
 4   Transport_Mode             5000 non-null   str
 5   Product_Category           5000 non-null   str
 6   Distance_km                5000 non-null   float64
 7   Weight_MT                  5000 non-null   float64
 8   Fuel_Price_Index           5000 non-null   float64
 9   Geopolitical_Risk_Score    5000 non-null   float64
 10  Weather_Condition          5000 non-null   str
 11  Carrier_Reliability_Score  5000 non-null   float64
 12  Lead_Time_Days             5000 non-null   float64
 13  Disruption_Occurred        5000 non-null   bool
dtypes: bool(1), datetime64[s](1), float64(6), str(6)
memory usage: 512.8 KB

In [19]:
df["Date"] = pd.to_datetime(df["Date"])

In [20]:
df.isna().sum()

Shipment_ID                  0
Date                         0
Origin_Port                  0
Destination_Port             0
Transport_Mode               0
Product_Category             0
Distance_km                  0
Weight_MT                    0
Fuel_Price_Index             0
Geopolitical_Risk_Score      0
Weather_Condition            0
Carrier_Reliability_Score    0
Lead_Time_Days               0
Disruption_Occurred          0
dtype: int64

In [21]:
df.duplicated().sum()

np.int64(0)

In [22]:
df.describe()

,Date,Distance_km,Weight_MT,Fuel_Price_Index,Geopolitical_Risk_Score,Carrier_Reliability_Score,Lead_Time_Days
count,5000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,2025-01-04 20:34:04,7704.063888,246.252052,2.854552,5.076900,0.754387,19.355386
min,2024-01-01 00:00:00,500.170000,1.030000,1.200000,0.000000,0.500000,0.500000
25%,2024-07-03 00:00:00,4036.010000,124.330000,2.020000,2.600000,0.629000,2.110000
50%,2025-01-06 00:00:00,7750.125000,243.500000,2.840000,5.100000,0.757000,8.245000
75%,2025-07-09 00:00:00,11347.462500,366.955000,3.710000,7.500000,0.879000,21.207500
max,2025-12-31 00:00:00,14995.910000,499.750000,4.500000,10.000000,1.000000,236.390000
std,NaN,4199.687885,142.522591,0.959533,2.877832,0.144363,31.405143

In [16]:
df['Disruption_Occurred'].value_counts()

Disruption_Occurred
True     3063
False    1937
Name: count, dtype: int64

In [17]:
for col in ["Origin_Port","Destination_Port","Transport_Mode",
            "Product_Category","Weather_Condition"]:
    print("\n", col)
    print(df[col].nunique())
    print(df[col].unique()[:20])

 Origin_Port
8
<StringArray>
[  'Singapore',   'Rotterdam',       'Busan',    'Shanghai',       'Dubai',
 'Los Angeles',     'Hamburg',     'Antwerp']
Length: 8, dtype: str

 Destination_Port
9
<StringArray>
['Los Angeles',    'Shanghai',     'Hamburg',   'Singapore',   'Marseille',
     'Antwerp',   'Rotterdam',       'Busan',       'Dubai']
Length: 9, dtype: str

 Transport_Mode
4
<StringArray>
['Rail', 'Air', 'Road', 'Sea']
Length: 4, dtype: str

 Product_Category
5
<StringArray>
['Textiles', 'Automotive', 'Perishables', 'Electronics', 'Pharmaceuticals']
Length: 5, dtype: str

 Weather_Condition
5
<StringArray>
['Hurricane', 'Storm', 'Rain', 'Fog', 'Clear']
Length: 5, dtype: str