In [1]:
import pandas as pd

In [2]:
data_path = '../data'

In [3]:
df_model=pd.read_pickle(data_path + '/processed/df_model.pkl')

In [7]:
df_model.head()

,Shipment_ID,Date,Origin_Port,Destination_Port,Transport_Mode,Product_Category,Distance_km,Weight_MT,Fuel_Price_Index,Geopolitical_Risk_Score,Weather_Condition,Carrier_Reliability_Score,Lead_Time_Days,Disruption_Occurred,Year,Month,Quarter,Route,Reliability_Level,Risk_Level
0,SC-10000,2025-10-16,Singapore,Los Angeles,Rail,Textiles,5930.83,197.42,2.43,5.0,Hurricane,0.865,41.39,1,2025,10,4,Singapore_to_Los Angeles,High,Medium
1,SC-10001,2024-04-24,Singapore,Shanghai,Rail,Automotive,14285.36,237.24,2.30,7.5,Storm,0.592,40.92,1,2024,4,2,Singapore_to_Shanghai,Low,High
2,SC-10002,2024-01-26,Rotterdam,Los Angeles,Rail,Perishables,11113.91,427.42,1.78,5.6,Rain,0.673,11.54,0,2024,1,1,Rotterdam_to_Los Angeles,Medium,Medium
3,SC-10003,2024-10-08,Busan,Hamburg,Rail,Electronics,9180.55,170.66,3.20,0.8,Hurricane,0.832,53.13,1,2024,10,4,Busan_to_Hamburg,Medium,Low
4,SC-10004,2024-09-07,Busan,Singapore,Air,Perishables,2762.27,434.96,2.77,1.9,Fog,0.741,0.50,1,2024,9,3,Busan_to_Singapore,Medium,Low

In [4]:
df_model["Date"].min(), df_model["Date"].max()

(Timestamp('2024-01-01 00:00:00'), Timestamp('2025-12-31 00:00:00'))

In [5]:
df_model["Year"].value_counts()

Year
2025    2545
2024    2455
Name: count, dtype: int64

In [6]:
pd.crosstab(
    df_model["Transport_Mode"],
    df_model["Disruption_Occurred"],
    normalize="index"
)*100

Disruption_Occurred          0          1
Transport_Mode
Air                  38.257576  61.742424
Rail                 38.818565  61.181435
Road                 38.962109  61.037891
Sea                  38.953942  61.046058

In [19]:
pd.crosstab(
    df_model["Weather_Condition"],
    df_model["Disruption_Occurred"],
    normalize="index"
)*100

Disruption_Occurred          0           1
Weather_Condition
Clear                63.015075   36.984925
Fog                  51.930502   48.069498
Hurricane             0.000000  100.000000
Rain                 58.034800   41.965200
Storm                20.459082   79.540918

In [20]:
df_model.groupby(
    "Weather_Condition"
)["Lead_Time_Days"].mean()

Weather_Condition
Clear         6.698704
Fog           9.892847
Hurricane    53.501848
Rain          7.736049
Storm        19.299182
Name: Lead_Time_Days, dtype: float64

In [21]:
df_model.groupby(
    "Transport_Mode"
)["Lead_Time_Days"].mean()

Transport_Mode
Air      1.644273
Rail    19.954253
Road    16.452306
Sea     39.802966
Name: Lead_Time_Days, dtype: float64