In [3]:
import pandas as pd

In [1]:
data_path = '../data'

In [16]:
df_model=pd.read_pickle(data_path + '/processed/df_model.pkl')

In [17]:
df_model["Date"].min(), df_model["Date"].max()

(Timestamp('2024-01-01 00:00:00'), Timestamp('2025-12-31 00:00:00'))

In [ ]:
df_model["Year"].value_counts()

In [18]:
pd.crosstab(
    df_model["Transport_Mode"],
    df_model["Disruption_Occurred"],
    normalize="index"
)*100

Disruption_Occurred          0          1
Transport_Mode
Air                  38.257576  61.742424
Rail                 38.818565  61.181435
Road                 38.962109  61.037891
Sea                  38.953942  61.046058

In [19]:
pd.crosstab(
    df_model["Weather_Condition"],
    df_model["Disruption_Occurred"],
    normalize="index"
)*100

Disruption_Occurred          0           1
Weather_Condition
Clear                63.015075   36.984925
Fog                  51.930502   48.069498
Hurricane             0.000000  100.000000
Rain                 58.034800   41.965200
Storm                20.459082   79.540918

In [20]:
df_model.groupby(
    "Weather_Condition"
)["Lead_Time_Days"].mean()

Weather_Condition
Clear         6.698704
Fog           9.892847
Hurricane    53.501848
Rain          7.736049
Storm        19.299182
Name: Lead_Time_Days, dtype: float64

In [21]:
df_model.groupby(
    "Transport_Mode"
)["Lead_Time_Days"].mean()

Transport_Mode
Air      1.644273
Rail    19.954253
Road    16.452306
Sea     39.802966
Name: Lead_Time_Days, dtype: float64