In [1]:
import pandas as pd

In [2]:
data_path = "../data"

In [3]:
df_model=pd.read_pickle(data_path + '/processed/df_model.pkl')

In [4]:
pd.cut(
    df_model["Geopolitical_Risk_Score"],
    bins=[0,3,7,10],
    labels=["Low","Medium","High"]
).to_frame("Risk_Bucket").join(
    df_model["Disruption_Occurred"]
).groupby("Risk_Bucket")[
    "Disruption_Occurred"
].mean()*100

Risk_Bucket
Low       47.685835
Medium    61.705274
High      73.670387
Name: Disruption_Occurred, dtype: float64

In [5]:
pd.cut(
    df_model["Carrier_Reliability_Score"],
    bins=[0,0.65,0.85,1],
    labels=["Low","Medium","High"]
).to_frame("Reliability_Bucket").join(
    df_model["Disruption_Occurred"]
).groupby("Reliability_Bucket")[
    "Disruption_Occurred"
].mean()*100

Reliability_Bucket
Low       65.307533
Medium    62.313803
High      56.075374
Name: Disruption_Occurred, dtype: float64

In [6]:
df_model.groupby(
    "Transport_Mode"
)["Lead_Time_Days"].mean()

Transport_Mode
Air      1.644273
Rail    19.954253
Road    16.452306
Sea     39.802966
Name: Lead_Time_Days, dtype: float64

In [7]:
df_model.groupby(
    "Weather_Condition"
)["Lead_Time_Days"].mean()

Weather_Condition
Clear         6.698704
Fog           9.892847
Hurricane    53.501848
Rain          7.736049
Storm        19.299182
Name: Lead_Time_Days, dtype: float64

In [8]:
df_model.groupby("Transport_Mode")[
    ["Distance_km","Weight_MT","Lead_Time_Days"]
].mean()

                Distance_km   Weight_MT  Lead_Time_Days
Transport_Mode
Air             7764.006992  247.802470        1.644273
Rail            7810.036068  251.140793       19.954253
Road            7593.067381  244.870255       16.452306
Sea             7649.456417  241.441585       39.802966

In [9]:
pd.crosstab(
    df_model["Transport_Mode"],
    df_model["Disruption_Occurred"],
    normalize="index"
) * 100

Disruption_Occurred          0          1
Transport_Mode
Air                  38.257576  61.742424
Rail                 38.818565  61.181435
Road                 38.962109  61.037891
Sea                  38.953942  61.046058

In [10]:
df_model.groupby("Weather_Condition")[
    "Disruption_Occurred"
].mean() * 100

Weather_Condition
Clear         36.984925
Fog           48.069498
Hurricane    100.000000
Rain          41.965200
Storm         79.540918
Name: Disruption_Occurred, dtype: float64

In [11]:
df_model.groupby("Weather_Condition")[
    "Lead_Time_Days"
].mean()

Weather_Condition
Clear         6.698704
Fog           9.892847
Hurricane    53.501848
Rain          7.736049
Storm        19.299182
Name: Lead_Time_Days, dtype: float64

In [4]:
df_model["Lead_Time_Days"].describe()

count    5000.000000
mean       19.355386
std        31.405143
min         0.500000
25%         2.110000
50%         8.245000
75%        21.207500
max       236.390000
Name: Lead_Time_Days, dtype: float64